# Generated by Django 5.0.6 on 2024-07-04 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_alter_food_name_en_alter_food_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsifi'),
        ),
    ]
