# Generated by Django 5.0.7 on 2024-07-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_alter_food_description_en_alter_food_description_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='img_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
