from environs import Env

env = Env()
BASE_URL = 'http://127.0.0.1:8000'
COMMENT_SEND_ID = env.str('COMMENT_SEND_ID') # comment id
COMMENT_MESSAGE_THREAD_ID = env.str('COMMENT_MESSAGE_THREAD_ID') # comment thread id
ORDER_SEND_CHAT = env.str('ORDER_SEND_CHAT') # order id
ORDER_TAKE_MESSAGE_THREAD_ID = env.str('ORDER_TAKE_MESSAGE_THREAD_ID')
ORDER_DELIVERY_MESSAGE_THREAD_ID = env.str('ORDER_DELIVERY_MESSAGE_THREAD_ID')


KITCHEN_LAN = 40.7128
KITCHEN_LON = -74.0060
